name: test_ap1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  dio: ^5.4.1
  json_annotation: ^4.8.1
  nfc_manager: ^3.3.0
  convert: ^3.1.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.0


flutter:
  assets:
    - lib/resources/assets/



  uses-material-design: true


flutter_intl:
  enabled: true
